spring.application.name=demo
# Health URL
monitor.url=http://localhost:8080/actuator/health

# Scheduler
monitor.interval=300000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=studiopathania@gmail.com
spring.mail.password=pbyvolidpsqxerhe

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.protocol=smtp
monitor.mail.to=bharatpathania700@gmail.com